name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

env:
  AZURE_WEBAPP_NAME: personal-blog-app    # 替换为你的 Azure 应用服务名称
  NODE_VERSION: '18.x'         # Node.js 版本
  JAVA_VERSION: '21'           # Java 版本

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    # 安装和构建前端
    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        chmod +x ./node_modules/.bin/vite  # 添加执行权限
        npx vite --version  # 检查 vite 是否可用
        npm run build

    # 设置 Java 环境
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'

    # 构建后端
    - name: Build Backend
      run: |
        cd backend
        mvn clean package -DskipTests

    # 部署到 Azure 应用服务
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend/target/*.jar
